# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: gateway                 # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Anbindung von Squeezebox Devices. Eine laufender Logitech Media Server wird benötigt.'
        en: 'Connects Squeezebox devices through a running Logitech Media Server'
    maintainer: Robert
    tester: onkelandy, Sandman60, cmalo, brandst
    state: ready
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/28692-√-neues-plugin-logitech-squeezebox-anregungen

    version: 1.3.0                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: Squeezebox          # class containing the plugin

parameters:
# Definition of parameters to be configured in etc/plugin.yaml

#    def __init__(self, smarthome, host='127.0.0.1', port=9090):


    host:
        type: str
        default: '127.0.0.1'
        description:
            de: 'Adresse (IP oder hostname) des Logitech Media Servers'
            en: 'Address (IP or hostname) of the Logitech Media Server'

    port:
        type: int
        default: 9090
        valid_min: 0
        valid_max: 65535
        description:
            de: 'Port Nummer des Logitech Media Servers'
            en: 'Port number of the Logitech Media Server'


item_attributes:
# Definition of item attributes defined by this plugin

plugin_functions: NONE
# Definition of plugin functions defined by this plugin

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

